---
- name: FDPG Backend
  tags: backend
  block:
  - name: FDPG Backend - Copy environment files
    copy:
      src: "{{ project_path }}/.env.default"
      dest: "{{ project_path }}/.env"
      remote_src: true

  - name: FDPG Backend - Upload secrets
    include_role:
      name: common
      tasks_from: get-storage-file
    vars:
      storage_file_path: "{{ item.src }}"
      host_file_path: "{{ item.dest }}"
    loop:
    - src:  "secrets/{{ env }}/dsf/fdpg/backend.fdpg.{{ env }}.ffg.de.p12"
      dest: "{{ secrets_path }}/backend.fdpg.{{ env }}.ffg.de.p12"
    - src:  "secrets/{{ env }}/domain/trusted_cas.pem"
      dest: "{{ secrets_path }}/trusted_cas.pem"

  - name: FDPG Backend - Setup evnironment variables
    include_role:
      name: common
      tasks_from: set-env
    vars:
      path: "{{ project_path }}/.env"
      variables:
      - name: FEASIBILITY_BACKEND_API_BASE_URL
        value:   "https://{{ fdpg_portal_domain }}/api/"
      - name: FEASIBILITY_BACKEND_ALLOWED_ORIGINS
        value:   "https://{{ fdpg_portal_domain }}"
      - name: FEASIBILITY_BACKEND_BROKER_CLIENT_DIRECT_ENABLED
        value:   "false"
      - name: FEASIBILITY_BACKEND_AKTIN_ENABLED
        value:   "false"
      - name: FEASIBILITY_BACKEND_DSF_ENABLED
        value:   "true"
      - name: FEASIBILITY_BACKEND_CERTS_PATH
        value: "{{ secrets_path }}"
      - name: FEASIBILITY_BACKEND_DSF_CACERT
        value:   "/opt/codex-feasibility-security/trusted_cas.pem"
      - name: FEASIBILITY_BACKEND_DSF_DSF_SECURITY_KEYSTORE_P12FILE
        value:   "/opt/codex-feasibility-security/backend.fdpg.{{ env }}.ffg.de.p12"
      - name: FEASIBILITY_BACKEND_DSF_ORGANIZATION_ID
        value:   "forschen-fuer-gesundheit.de"
      - name: FEASIBILITY_BACKEND_DSF_WEBSERVICE_BASE_URL
        value:   "https://{{ fdpg_portal_dsf_domain }}/fhir"
      - name: FEASIBILITY_BACKEND_DSF_WEBSOCKET_URL
        value:   "wss://{{ fdpg_portal_dsf_domain }}:443/fhir/ws"
      - name: FEASIBILITY_BACKEND_KEYCLOAK_BASE_URL_ISSUER
        value:   "https://{{ fdpg_auth_domain }}"
      - name: FEASIBILITY_BACKEND_KEYCLOAK_BASE_URL_JWK
        value:   "https://{{ fdpg_auth_domain }}"

  - name: FDPG Backend - Start containers
    community.docker.docker_compose_v2:
      project_src: "{{ project_path }}"
      project_name: "{{ project_name }}"
    environment:
      COMPOSE_IGNORE_ORPHANS: "1"
