---
- name: FDPG GUI
  tags: gui
  block:
  - name: FDPG GUI - Copy Default Deploy Configuration
    copy:
      src: "{{ project_path }}/deploy-config.json.default"
      dest: "{{ project_path }}/deploy-config.json"
      remote_src: true

  - name: FDPG GUI - Set Auth Base URL
    replace:
      path: "{{ project_path }}/deploy-config.json"
      after: '{{ item.after }}'
      before: '{{ item.before }}'
      regexp: '{{ item.regexp }}'
      replace: '{{ item.replace }}'
    loop:
    - after: '\s*"auth"'
      before: '\s*"legal"'
      regexp: '\s*"baseUrl":\s*"https://example.org.*"'
      replace: '"baseUrl": "https://{{ fdpg_auth_domain }}"'
    - after: '\s*"uiBackendApi"'
      before: '\s*"auth"'
      regexp: '\s*"baseUrl":\s*"https://.*localhost.*/api/v4"'
      replace: '"baseUrl": "https://{{ fdpg_portal_domain }}/api/v4"'

  - name: FDPG GUI - Start GUI
    community.docker.docker_compose_v2:
      project_src: "{{ project_path }}"
      project_name: "{{ project_name }}"
      recreate: "always"
    environment:
      COMPOSE_IGNORE_ORPHANS: "1"
