---
- name: FDPG GUI
  tags: gui
  block:
  - name: FDPG GUI - Copy Default Deploy Configuration
    copy:
      src: "{{ project_path }}/deploy-config.json.default"
      dest: "{{ project_path }}/deploy-config.json"
      remote_src: true

  - name: FDPG GUI - Set Configuration
    replace:
      path: "{{ project_path }}/deploy-config.json"
      regexp: '{{ item.regexp }}'
      replace: '{{ item.replace }}'
    loop:
    - regexp: '"authBaseUrl":\s*"https://.*"'
      replace: '"authBaseUrl": "https://{{ fdpg_auth_domain }}"'
    - regexp: '"backendBaseUrl":\s*"https://.*"'
      replace: '"backendBaseUrl": "https://{{ fdpg_portal_domain }}"'
    - regexp: '"authClientId":\s*".*"'
      replace: '"authClientId": "{{ fdpg_auth_client_id }}"'
    - regexp: '"authRealm":\s*".*"'
      replace: '"authRealm": "{{ fdpg_auth_realm }}"'

  - name: FDPG GUI - Start GUI
    community.docker.docker_compose_v2:
      project_src: "{{ project_path }}"
      project_name: "{{ project_name }}"
      recreate: "always"
    environment:
      COMPOSE_IGNORE_ORPHANS: "1"
