---
# tasks file for fdpg-portal
- name: Checkout FDPG Deployment
  include_role:
    name: common
    tasks_from: checkout-deploy-repo
  vars:
    feasibility_deploy_version: readd-dsf

- name: Setup Certificate
  include_role:
    name: common
    tasks_from: certbot
  vars:
    certbot_register_email: mathias.ruehle@uni-leipzig.de
    certbot_register_domain: "{{ fdpg_portal_domain }}"
    certbot_register_sans:
    - "{{ fdpg_portal_aktin_domain }}"
    - "{{ fdpg_portal_dsf_domain }}"

- name: Configure NGINX
  template:
    src: nginx.conf.j2
    dest: /home/ubuntu/deploy/feasibility-portal/gui/nginx.conf
    owner: ubuntu
    group: ubuntu
    mode: u=rw,g=r,o=r
