---
# tasks file for fdpg-portal
- name: Checkout FDPG Deployment
  include_role:
    name: common
    tasks_from: checkout-deploy-repo
  vars:
    feasibility_deploy_version: "{{ deploy_version }}"
  tags:
  - common

- name: Deploy Proxy
  include_tasks: proxy.yml
  vars:
    project_path: "{{ deploy_path }}/feasibility-portal/proxy"
    project_name: fdpg
  tags: proxy

- name: Deploy DSF
  include_tasks: dsf.yml
  vars:
    project_path: "{{ deploy_path }}/feasibility-portal/dsf"
    project_name: fdpg
  tags: dsf

- name: Deploy backend
  include_tasks: backend.yml
  vars:
    project_path: "{{ deploy_path }}/feasibility-portal/backend"
    project_name: fdpg
  tags: backend

- name: Deploy GUI
  include_tasks: gui.yml
  vars:
    project_path: "{{ deploy_path }}/feasibility-portal/gui"
    project_name: fdpg
  tags: gui
