---
# tasks file for fdpg-portal
- name: Checkout FDPG Deployment
  include_role:
    name: common
    tasks_from: checkout-deploy-repo
  vars:
    feasibility_deploy_version: readd-dsf

- name: Deploy aktin broker
  include_tasks: aktin-broker.yml
  vars:
    aktin_broker_path: "{{ deploy_path }}/feasibility-portal/aktin-broker"
    project_name: fdpg

- name: Deploy DSF
  include_tasks: dsf.yml
  vars:
    dsf_path: "{{ deploy_path }}/feasibility-portal/dsf-broker"
    project_name: fdpg
    plugins:
    - name: ping-pong
      url: "https://github.com/datasharingframework/dsf-process-ping-pong"
      version: "{{ dsf_process_ping_pong_version }}"
      file:
        basename: "dsf-process-ping-pong"
        extension: "jar"
    - name: feasibility
      url: "https://github.com/medizininformatik-initiative/feasibility-dsf-process"
      version: "{{ dsf_process_feasibility_version }}"
      file:
        basename: "feasibility-dsf-process"
        extension: "jar"

- name: Deploy backend
  include_tasks: backend.yml
  vars:
    backend_path: "{{ deploy_path }}/feasibility-portal/backend"
    project_name: fdpg

- name: Deploy GUI
  include_tasks: gui.yml
  vars:
    gui_path: "{{ deploy_path }}/feasibility-portal/gui"
    project_name: fdpg
