---
- name: Install Docker on Ubuntu 22.04
  hosts: all
  become: true
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-jmespath
      state: present

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: Install Docker
    apt:
      name: docker-ce
      state: present

  # Determine latest docker-compose version once per run and set fact 'docker_compose_version' if not given
  - block:
    - name: Determine latest GitHub release (local)
      delegate_to: localhost
      become: false
      uri:
        url: "https://api.github.com/repos/docker/compose/releases"
        body_format: json
      register: _github_releases
      until: _github_releases.status == 200
      retries: 5

    - name: Set consul_version
      set_fact:
        docker_compose_version: "{{ _github_releases.json
          | json_query('[?prerelease==`false` && draft==`false`].tag_name')
          | community.general.version_sort
          | last | regex_replace('^v?(.*)$', '\\1') }}"

    when: (docker_compose_version is not defined) or (docker_compose_version == 'latest')
    run_once: true


  - name: Install docker-compose
    get_url:
      url : https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x,o+x'
