galaxy_info:
  author: Mathias Rühle
  description: create linux user 'ubuntu'' and add ssh public keys of main developers to its authorized ssh keys
  company: Medizininformatik-Initiative
  license: Apache-2.0
  min_ansible_version: "2.1"
  platforms:
  - name: Ubuntu
    versions:
    - all
  galaxy_tags: []

dependencies: []
