---
- name: Read admin password
  set_fact:
    kc_admin_password: "{{ lookup('file', storage_path + '/secrets/' + env + '/keycloak/keycloak-admin.password') }}"
  changed_when: false

- name: Get Keycloak auth token
  uri:
    url: https://{{ fdpg_auth_domain }}/realms/master/protocol/openid-connect/token
    method: POST
    validate_certs: false
    body: "username=admin&password={{ kc_admin_password }}&grant_type=password&client_id=admin-cli"
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: access_token_result

- name: Extract Keycloak auth token
  set_fact:
    access_token_bearer: "{{ access_token_result.json | json_query('access_token') }}"

- name: Check for existing Keycloak client '{{ client_id }}'
  uri:
    url: https://{{ fdpg_auth_domain }}/admin/realms/dataportal/clients?clientId={{ client_id }}
    method: GET
    validate_certs: false
    status_code: 200
    headers:
      Authorization: "Bearer {{ access_token_bearer }}"
    return_content: true
  failed_when: keycloak_client_info.json is undefined or (keycloak_client_info.json | type_debug != 'list') or (keycloak_client_info.json | length == 0)
  register: keycloak_client_info

- name: Get Keycloak client secret of client '{{ client_id }}'
  uri:
    url: https://{{ fdpg_auth_domain }}/admin/realms/dataportal/clients/{{ keycloak_client_info.json | json_query("[?clientId=='" + client_id + "'].id | [0]") }}/client-secret
    method: GET
    validate_certs: false
    status_code: 200
    headers:
      Authorization: "Bearer {{ access_token_bearer }}"
    return_content: true
  failed_when: keycloak_client_secret.json is undefined or keycloak_client_secret.json.value is undefined
  register: keycloak_client_secret

- name: Keycloak - Set fact '{{ client_secret_var_name | default('client_secret') }}'
  set_fact: {"{{ client_secret_var_name | default('client_secret') }}": "{{ keycloak_client_secret.json.value }}"}
