---
- name: Restart Prometheus
  listen: "restart prometheus"
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    name: prometheus

- name: Restart Grafana
  listen: "restart grafana"
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    name: grafana
