---
- name: DIZ DSF BPE - Create folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "777"
  loop:
  - "{{ project_path }}/cache"
  - "{{ project_path }}/log"
  - "{{ project_path }}/process"
  - "{{ secrets_path }}"

- name: DIZ DSF BPE - Upload FHIR app secrets
  include_role:
    name: common
    tasks_from: get-storage-file
  vars:
    storage_file_path: "{{ item.src }}"
    host_file_path: "{{ item.dest }}"
  loop:
  - src:  "secrets/{{ env }}/dsf/diz-{{ instance }}/bpe.diz-{{ instance }}.{{ env }}.ffg.de.crt"
    dest: "{{ secrets_path }}/bpe.diz-{{ instance }}.{{ env }}.ffg.de.crt"
  - src:  "secrets/{{ env }}/dsf/diz-{{ instance }}/bpe.diz-{{ instance }}.{{ env }}.ffg.de.key"
    dest: "{{ secrets_path }}/bpe.diz-{{ instance }}.{{ env }}.ffg.de.key"
  - src:  "secrets/{{ env }}/domain/root-ca.local.crt"
    dest: "{{ secrets_path }}/root-ca.local.crt"
  - src:  "secrets/{{ env }}/domain/root-ca.local.jks"
    dest: "{{ secrets_path }}/root-ca.local.jks"
  - src:  "secrets/{{ env }}/dsf/diz-{{ instance }}/db_user.password"
    dest: "{{ secrets_path }}/db_user.password"
  - src:  "secrets/{{ env }}/dsf/diz-{{ instance }}/db_user_camunda.password"
    dest: "{{ secrets_path }}/db_user_camunda.password"
  - src:  "secrets/{{ env }}/dsf/diz-{{ instance }}/db_liquibase.password"
    dest: "{{ secrets_path }}/db_liquibase.password"
  - src:  "secrets/{{ env }}/domain/trusted_cas.pem"
    dest: "{{ secrets_path }}/trusted_cas.pem"
  - src:  "secrets/{{ env }}/domain/diz-{{ instance }}-triangle.local.htpasswd.password"
    dest: "{{ secrets_path }}/diz-{{ instance }}-triangle.local.htpasswd.password"

- name: DIZ DSF BPE - Read FHIR store basic authentication password
  slurp:
    src: "{{ secrets_path }}/diz-{{ instance }}-triangle.local.htpasswd.password"
  register: basic_auth_password_base64

- name: DIZ DSF BPE - Install process plugins
  include_role:
    name: common
    tasks_from: dsf-bpe-install-plugins
  vars:
    process_plugin_folder_path: "{{ project_path }}/process"
    process_plugins: "{{ dsf_process_plugins_install }}"
    process_scope: 'diz'

- name: DSF FHIR - Generate files from templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: ubuntu
    group: ubuntu
    mode: u+rw,g+r,o+r
  loop:
  - src: "docker-compose.yml.j2"
    dest: "{{ project_path }}/docker-compose.yml"
  - src: "dsf-bpe.env.default.j2"
    dest: "{{ project_path }}/bpe.env.default"
  vars:
    domain: "{{ lookup('vars', 'diz_' + diz_instance + '_dsf_domain' ) }}"
    basic_auth_password: "{{ basic_auth_password_base64.content | b64decode | trim }}"
    dsf_process_report_version_number: "{{ dsf_process_report_version | regex_replace('^(\\d+\\.\\d+)\\.\\d+\\.\\d+.*$', '\\1') }}"
    dsf_process_data_sharing_version_number: "{{ dsf_process_data_sharing_version | regex_replace('^(\\d+\\.\\d+)\\.\\d+\\.\\d+.*$', '\\1') }}"
    dsf_process_feasibility_version_number: "{{ dsf_process_feasibility_version | regex_replace('^(\\d+\\.\\d+)\\.\\d+\\.\\d+.*$', '\\1') }}"

