---
- name: DIZ DSF BPE - Upload FHIR app secrets
  include_role:
    name: common
    tasks_from: get-storage-file
  vars:
    storage_file_path: "{{ item.src }}"
    host_file_path: "{{ item.dest }}"
  loop:
  - src:  "secrets/dsf/diz-{{ instance }}/bpe.diz-{{ instance }}.test.ffg.de.cer"
    dest: "{{ secrets_path }}/bpe.diz-{{ instance }}.test.ffg.de.cer"
  - src:  "secrets/dsf/diz-{{ instance }}/bpe.diz-{{ instance }}.test.ffg.de.key"
    dest: "{{ secrets_path }}/bpe.diz-{{ instance }}.test.ffg.de.key"
  - src:  "secrets/domain/root-ca.local.jks"
    dest: "{{ secrets_path }}/root-ca.local.jks"
  - src:  "secrets/dsf/diz-{{ instance }}/db_bpe_user.password"
    dest: "{{ secrets_path }}/db_bpe_user.password"
  - src:  "secrets/dsf/diz-{{ instance }}/db_bpe_user_camunda.password"
    dest: "{{ secrets_path }}/db_bpe_user_camunda.password"
  - src:  "secrets/dsf/diz-{{ instance }}/db_fhir_user.password"
    dest: "{{ secrets_path }}/db_fhir_user.password"
  - src:  "secrets/dsf/diz-{{ instance }}/db_fhir_user_permanent_delete.password"
    dest: "{{ secrets_path }}/db_fhir_user_permanent_delete.password"
  - src:  "secrets/dsf/diz-{{ instance }}/db_liquibase.password"
    dest: "{{ secrets_path }}/db_liquibase.password"
  - src:  "secrets/domain/trusted_cas.pem"
    dest: "{{ secrets_path }}/trusted_cas.pem"
  - src:  "secrets/domain/diz-{{ instance }}-triangle.htpasswd.password"
    dest: "{{ secrets_path }}/diz-{{ instance }}-triangle.htpasswd.password"

- name: DIZ DSF BPE - Read FHIR store basic authentication password
  slurp:
    src: "{{ secrets_path }}/diz-{{ instance }}-triangle.htpasswd.password"
  register: basic_auth_password

- name: DIZ DSF BPE - Create folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "777"
  loop:
  - "{{ dsf_bpe_path }}/bpe/cache"
  - "{{ dsf_bpe_path }}/bpe/last_event"
  - "{{ dsf_bpe_path }}/bpe/log"
  - "{{ dsf_bpe_path }}/process"

- name: DIZ DSF BPE - Create dummy file
  file:
    path: "{{ dsf_bpe_path }}/bpe/dummy"
    state: touch
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "644"

- name: DIZ DSF BPE - Install process plugins
  include_role:
    name: common
    tasks_from: dsf-bpe-install-plugins
  vars:
    process_plugin_folder_path: "{{ dsf_bpe_path }}/process"
    process_plugins:
    - name: ping-pong
      url: "https://github.com/datasharingframework/dsf-process-ping-pong"
      version: "{{ dsf_process_ping_pong_version }}"
      file:
        basename: "dsf-process-ping-pong"
        extension: "jar"
    - name: feasibility
      url: "https://github.com/medizininformatik-initiative/feasibility-dsf-process"
      version: "{{ dsf_process_feasibility_version }}"
      file:
        basename: "feasibility-dsf-process"
        extension: "jar"
    - name: report
      url: "https://github.com/medizininformatik-initiative/mii-process-report"
      version: "{{ dsf_process_report_version }}"
      file:
        basename: "mii-process-report"
        extension: "jar"

- name: DIZ DSF BPE - Setup environment variables
  include_role:
    name: common
    tasks_from: set-env
  vars:
    path: "{{ dsf_bpe_path }}/.env"
    variables:
    - name: FEASIBILITY_DSF_CLIENT_PROCESS_ORGANIZATION_IDENTIFIER
      value: "{{ lookup('vars', 'diz_' + instance + '_dsf_domain') }}"
    - name: FEASIBILITY_DSF_FHIR_SERVER_BASE_URL
      value: "https://{{ lookup('vars', 'diz_' + instance + '_dsf_domain') }}/fhir"
    - name: FEASIBILITY_DSF_BPE_LOG_FOLDER_PATH
      value: "{{ dsf_bpe_path }}/bpe/log"
    - name: FEASIBILITY_DSF_BPE_LAST_EVENT_FOLDER_PATH
      value: "{{ dsf_bpe_path }}/bpe/last_event"
    - name: FEASIBILITY_DSF_BPE_CACHE_FOLDER_PATH
      value: "{{ dsf_bpe_path }}/bpe/cache"
    - name: FEASIBILITY_DSF_BPE_PROCESS_PLUGINS_DIRECTORY_PATH
      value: "{{ dsf_bpe_path }}/process"
    - name: FEASIBILITY_DSF_BPE_PROCESS_EXCLUDED
      value: |-
        medizininformatik-initiativede_feasibilityRequest|{{ dsf_process_feasibility_version | regex_replace('^(\d+\.\d+)\.\d+\.\d+.*$', '\1') }}
        medizininformatik-initiativede_reportReceive|{{ dsf_process_report_version | regex_replace('^(\d+\.\d+)\.\d+\.\d+.*$', '\1') }}
    - name: FEASIBILITY_DSF_CLIENT_TRUST_CERTIFICATES_FILE
      value: "{{ secrets_path }}/trusted_cas.pem"
    - name: FEASIBILITY_DSF_DB_LIQUIBASE_PASSWORD_FILE
      value: "{{ secrets_path }}/db_liquibase.password"
    - name: FEASIBILITY_DSF_BPE_DB_USER_PASSWORD_FILE
      value: "{{ secrets_path }}/db_bpe_user.password"
    - name: FEASIBILITY_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE
      value: "{{ secrets_path }}/db_bpe_user_camunda.password"
    - name: FEASIBILITY_DSF_CLIENT_CERTIFICATE_FILE
      value: "{{ secrets_path }}/bpe.diz-{{ instance }}.test.ffg.de.cer"
    - name: FEASIBILITY_DSF_CLIENT_CERTIFICATE_PRIVATE_KEY_FILE
      value: "{{ secrets_path }}/bpe.diz-{{ instance }}.test.ffg.de.key"
    - name: FEASIBILITY_DSF_FHIR_DB_USER_PASSWORD_FILE
      value: "{{ secrets_path }}/db_fhir_user.password"
    - name: FEASIBILITY_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE
      value: "{{ secrets_path }}/db_fhir_user_permanent_delete.password"
    - name: FEASIBILITY_DSF_PROXY_CERTIFICATE_AND_INTERMEDIATE_CAS_FILE
      value: "{{ dsf_bpe_path }}/bpe/dummy"
    - name: FEASIBILITY_DSF_PROXY_CERTIFICATE_PRIVATE_KEY_FILE
      value: "{{ dsf_bpe_path }}/bpe/dummy"
    - name: FEASIBILITY_DSF_PROXY_TRUSTED_CLIENT_CAS_FILE
      value: "{{ dsf_bpe_path }}/bpe/dummy"
    - name: FEASIBILITY_DSF_CLIENT_PROCESS_EVALUATION_STRATEGY
      value: "{{ evaluation_strategy }}"
    - name: FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_BASE_URL
      value: "https://triangle.diz.local/fhir/"
    - name: FEASIBILITY_DSF_CLIENT_PROCESS_EVALUATION_OBFUSCATE
      value: "true"
    - name: FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_BASIC_AUTH_USERNAME
      value: "test"
    - name: FEASIBILITY_DSF_CLIENT_PROCESS_FHIR_SERVER_BASIC_AUTH_PASSWORD
      value: "{{ basic_auth_password.content | b64decode | trim }}"
    - name: FEASIBILITY_DSF_CLIENT_PROCESS_TRUST_STORE_PATH
      value: "/run/secrets/root_ca.local.jks"
    - name: FEASIBILITY_DSF_CLIENT_PROCESS_TRUST_STORE_PASSWORD
      value: "password"

- name: DIZ DSF BPE - Remove proxy dependency and enable client store environment variables
  lineinfile:
    path: "{{ dsf_bpe_path }}/docker-compose.yml"
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    backrefs: true
  loop:
  - regexp: '^(\s*)- dsf-dic-fhir-proxy\s*'
    line: '\1#- dsf-dic-fhir-proxy'
  - regexp: '^(\s*)#\s*(.*)CLIENT_STORE_AUTH_BASIC_USERNAME(.*)$'
    line: '\1\2CLIENT_STORE_AUTH_BASIC_USERNAME\3'
  - regexp: '^(\s*)#\s*(.*)CLIENT_STORE_AUTH_BASIC_PASSWORD(.*)$'
    line: '\1\2CLIENT_STORE_AUTH_BASIC_PASSWORD\3'
  - regexp: '^(\s*)#\s*(.*)CLIENT_STORE_TRUST_STORE_PATH(.*)$'
    line: '\1\2CLIENT_STORE_TRUST_STORE_PATH\3'
  - regexp: '^(\s*)#\s*(.*)CLIENT_STORE_TRUST_STORE_PASSWORD(.*)$'
    line: '\1\2CLIENT_STORE_TRUST_STORE_PASSWORD\3'

- name: DIZ DSF BPE - Add local ca trust store
  lineinfile:
    path: "{{ dsf_bpe_path }}/docker-compose.yml"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
  loop:
  - insertafter: "^secrets:"
    line: '  root_ca.local.jks: { file: "{{ secrets_path }}/root-ca.local.jks" }'
  - insertafter: "^    - db_dic_1_bpe_user_camunda.password"
    line: '    - root_ca.local.jks'
