---
- name: DSF BPE - Set host variables
  set_fact:
    diz_instance: "{{ inventory_hostname | regex_replace('^.*-diz-(\\d+)-(.*)$', '\\1') }}"
    project_path: "{{ deploy_path }}/dsf-bpe"
  failed_when: inventory_hostname is not regex('^.*-diz-\d+-.*$')

- name: DSF BPE - Configure BPE app
  include_tasks: bpe-app.yml
  vars:
    instance: "{{ diz_instance }}"
    evaluation_strategy: "{{ feasibility_evaluation_strategy | default('cql') }}"
    evaluation_obfuscate: "{{ feasibility_evaluation_obfuscate | default(true) | string | lower }}"

- name: DSF BPE - Start container
  community.docker.docker_compose_v2:
    project_src: "{{ project_path }}"
    project_name: "diz-{{ diz_instance }}"
