galaxy_info:
  author: Mathias Rühle
  description: setup HiGHmed DSF BPE service
  company: Medizininformatik-Initiative
  license: Apache-2.0
  min_ansible_version: "2.1"
  platforms:
  - name: Ubuntu
    versions:
    - all
  galaxy_tags: []

dependencies: []
