---
- name: Add ubuntu user
  user:
    name: "ubuntu"
    shell: /bin/bash
    createhome: yes
    groups: sudo,docker

- name: Add SSH keys for users
  authorized_key:
    user: "ubuntu"
    key: "{{ ssh_keys[item].key }}"
  when:
  - item is defined
  - ssh_keys[item] is defined
  loop: "{{ add_authorized_keys | default([]) }}"
  loop_control:
    label: "{{ item }} ({{ ssh_keys[item].name if ssh_keys[item] is defined else 'UNKNOWN' }})"
