services:
  nginx:
    image: 'nginxinc/nginx-unprivileged:1.25.4-alpine'
    restart: unless-stopped
    networks:
    - keycloak_default
    ports:
    - "443:8443"
    volumes:
    - "{{ certificate_path }}:/etc/nginx/cert.pem:ro"
    - "{{ private_key_path }}:/etc/nginx/pkey.pem:ro"
    - "{{ deploy_path }}/nginx.conf:/etc/nginx/nginx.conf:ro"
networks:
  keycloak_default:
    external: true
