- name: Common Setup
  hosts: all
  become: true
  roles:
  - docker
  - role: user-ubuntu
    vars:
      add_authorized_keys:
      - akiel
      - jgruendner
      - mruehle

- name: Add additional ssh keys to FDPG and DIZ
  hosts:
  - portal
  - keycloak
  - diz_triangle
  - diz_dsf_fhir
  - diz_dsf_bpe
  - dms
  roles:
  - role: user-ubuntu
    vars:
      add_authorized_keys:
      - rwettstein

- name: Setup DIZ internal network
  hosts:
  - diz_dsf_bpe
  - diz_triangle
  tasks:
  - name: Add bpe entry to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "10.0.0.2 bpe.diz.local"
      state: present
  - name: Add triangle entry to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "10.0.0.3 triangle.diz.local"
      state: present

- name: Setup FDPG Portal
  hosts: portal
  roles:
  - fdpg-portal

- name: Setup FDPG Auth Server
  hosts: keycloak
  roles:
  - fdpg-keycloak

- name: Setup DIZ Triangle
  hosts: diz_triangle
  roles:
  - diz-triangle

- name: Setup DIZ DSF FHIR
  hosts: diz_dsf_fhir
  roles:
  - diz-dsf-fhir

- name: Setup DIZ DSF BPE
  hosts: diz_dsf_bpe
  roles:
  - diz-dsf-bpe

- name: Setup Monitoring
  hosts: monitoring
  become: true
  roles:
  - monitoring

- name: Setup Perf Test
  hosts: perf_test
  become: true
  roles:
  - perf-test
  - blazectl
  - role: blaze-repo
    become_user: ubuntu

- name: Setup MII FHIR Server
  hosts: mii-fhir
  roles:
  - fhir-server

- name: Setup Datenmanagementstelle (DMS)
  hosts: dms
  roles:
  - dms
