- name: Flare
  tags: flare
  block:
  - name: Flare - Get environment config stats
    stat:
      path: "{{ project_path }}/.env"
    register: flare_env

  - name: Flare - Get default environment config stats
    stat:
      path: "{{ project_path }}/.env.default"
    register: flare_env_default

  - name: Flare - Copy default environment config
    copy:
      src: "{{ project_path }}/.env.default"
      dest: "{{ project_path }}/.env"
      owner: ubuntu
      group: ubuntu
      mode: u+rw,g-wx,o-rwx
      remote_src: true
    when: flare_env.stat.exists == false or flare_env.stat.ctime < flare_env_default.stat.ctime

  - name: Flare - Setup evnironment variables
    include_role:
      name: common
      tasks_from: set-env
    vars:
      path: "{{ project_path }}/.env"
      variables:
      - name: FLARE_LOG_LEVEL
        value: "{{ 'debug' if enable_debug is defined and enable_debug == 'true' else 'info' }}"

  - name: Flare - Start container
    community.docker.docker_compose_v2:
      project_src: "{{ project_path }}"
      project_name: "{{ project_name }}"
    environment:
      COMPOSE_IGNORE_ORPHANS: "1"
