---
# tasks file for diz
- name: DIZ Triangle - Checkout FDPG Deployment
  include_role:
    name: common
    tasks_from: checkout-deploy-repo
  vars:
    feasibility_deploy_version: "{{ deploy_version }}"
  tags: common

- name: DIZ Triangle - Extract DIZ instance from hostname
  set_fact:
    diz_instance: "{{ inventory_hostname | regex_replace('^.*-diz-(\\d+)-.*$', '\\1') }}"
  failed_when: inventory_hostname is not regex('^.*-diz-\d+-.*$')

- name: DIZ Triangle - Deploy FHIR server
  include_tasks: fhir-server.yml
  vars:
    project_path: "{{ deploy_path }}/feasibility-triangle/fhir-server"
    project_name: triangle
  tags: fhir

- name: DIZ Triangle - Deploy flare
  include_tasks: flare.yml
  vars:
    project_path: "{{ deploy_path }}/feasibility-triangle/flare"
    project_name: triangle
  tags: flare

- name: DIZ Triangle - Deploy reverse proxy
  include_tasks: rev-proxy.yml
  vars:
    project_path: "{{ deploy_path }}/feasibility-triangle/rev-proxy"
    project_name: triangle
  tags: proxy

- name: DIZ Triangle - Deploy aktin client
  include_tasks: aktin-client.yml
  vars:
    project_path: "{{ deploy_path }}/feasibility-triangle/aktin-client"
    project_name: triangle
  when: aktin is defined and aktin == "true"
  tags: aktin
