---
# tasks file for diz
- name: DIZ Data Node - Checkout FDPG Deployment
  include_role:
    name: common
    tasks_from: checkout-deploy-repo
  tags: common

- name: DIZ Data Node - Extract DIZ instance from hostname
  set_fact:
    diz_instance: "{{ inventory_hostname | regex_replace('^.*-diz-(\\d+)-.*$', '\\1') }}"
  failed_when: inventory_hostname is not regex('^.*-diz-\d+-.*$')
  tags:
  - common
  - fhir
  - flare
  - proxy

- name: DIZ Data Node - Get Keycloak client secret
  set_fact:
    issuer_url: "https://{{ fdpg_auth_domain + (fdpg_auth_context | regex_replace('/$', '')) }}/realms/{{ fdpg_auth_realm }}"
    client_id: "{{ blaze_auth_client_id }}"
    client_secret: "{{ lookup('file', storage_path + '/secrets/' + env + '/keycloak/keycloak-' + blaze_auth_client_id + '.password') }}"
  
- name: DIZ Data Node - Deploy FHIR server
  include_tasks: fhir-server.yml
  vars:
    project_path: "{{ deploy_path }}/data-node/fhir-server"
    project_name: dataportal
  tags: fhir

- name: DIZ Data Node - Deploy flare
  include_tasks: flare.yml
  vars:
    project_path: "{{ deploy_path }}/data-node/flare"
    project_name: dataportal
  tags: flare
  when: feasibility_evaluation_strategy == 'ccdl'

- name: DIZ Data Node - Deploy Torch
  include_tasks: torch.yml
  vars:
    project_path: "{{ deploy_path }}/data-node/torch"
    project_name: dataportal
  tags: torch
  when: enable_torch | default(false)

- name: DIZ Data Node - Deploy Terminology Server
  include_tasks: terminology_server.yml
  vars:
    project_path: "{{ deploy_path }}/data-node/terminology-server"
    project_name: dataportal
  tags: terminology-server
  when: enable_terminology_server | default(false)

- name: DIZ Data Node - Deploy FHIR Pseudonymizer
  include_tasks: fhir-pseudonymizer.yml
  vars:
    project_path: "{{ deploy_path }}/data-node/fhir-pseudonymizer"
    project_name: dataportal
  tags: fhir-pseudonymizer
  when: enable_fhir_pseudonymizer | default(false)

- name: DIZ Data Node - Deploy FHIR Flattener
  include_tasks: fhir-flattener.yml
  vars:
    project_path: "{{ deploy_path }}/data-node/fhir-flattener"
    project_name: dataportal
  tags: fhir-flattener
  when: enable_fhir_flattener | default(false)

- name: DIZ Data Node - Deploy FHIR Validator
  include_tasks: fhir-validator.yml
  vars:
    project_path: "{{ deploy_path }}/data-node/fhir-validator"
    project_name: dataportal
  tags: fhir-validator
  when: enable_fhir_validator | default(false)

- name: DIZ Data Node - Deploy reverse proxy
  include_tasks: rev-proxy.yml
  vars:
    project_path: "{{ deploy_path }}/data-node/rev-proxy"
    project_name: dataportal
  tags: proxy
