- name: TORCH
  tags: torch
  block:
  - name: TORCH - Get environment config stats
    stat:
      path: "{{ project_path }}/.env"
    register: torch_env

  - name: TORCH - Upload secrets
    include_role:
      name: common
      tasks_from: get-storage-file
    vars:
      storage_file_path: "{{ item.src }}"
      host_file_path: "{{ item.dest }}"
    loop:
    - src:  "secrets/{{ env }}/domain/trusted_cas.pem"
      dest: "{{ project_path }}/../auth/trusted_cas.pem"


  - name: TORCH - Read 'trusted_cas.pem'
    set_fact:
      cas_content: "{{ lookup('file', storage_path + '/secrets/' + env + '/domain/trusted_cas.pem') }}"

  - name: TORCH - Split CAs in list
    set_fact:
      ca_list: "{{ cas_content | regex_findall('(?s)-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----') }}"

  - name: TORCH - Write each certificate to its own PEM file
    copy:
      content: "{{ item }}"
      dest: "{{ project_path }}/../auth/trusted_ca_{{ '%02d' % (idx + 1) }}.pem"
      mode: '0644'
    loop: "{{ ca_list }}"
    loop_control:
      index_var: idx
      label: "trusted_ca_{{ '%02d' % (idx + 1) }}.pem"

  - name: TORCH - Get default environment config stats
    stat:
      path: "{{ project_path }}/.env.default"
    register: torch_env_default

  - name: TORCH - Copy default environment config
    copy:
      src: "{{ project_path }}/.env.default"
      dest: "{{ project_path }}/.env"
      owner: ubuntu
      group: ubuntu
      mode: u+rw,g-wx,o-rwx
      remote_src: true
    when: torch_env.stat.exists == false or torch_env.stat.ctime < torch_env_default.stat.ctime

  - name: TORCH - Setup environment variables
    include_role:
      name: common
      tasks_from: set-env
    vars:
      path: "{{ project_path }}/.env"
      variables:
      - name: TORCH_NGINX_PORT
        value: "127.0.0.1:8180"
      - name: TORCH_OUTPUT_FILE_SERVER_URL
        value: "http://localhost:8180"
      - name: TORCH_FHIR_OAUTH_ISSUER_URI
        value: "{{ issuer_url }}"
      - name: TORCH_FHIR_OAUTH_CLIENT_ID
        value: "{{ client_id }}"
      - name: TORCH_FHIR_OAUTH_CLIENT_SECRET
        value: "{{ client_secret }}"
      - name: TORCH_USE_CQL
        value: "true"
      - name: LOG_LEVEL
        value: "{{ 'debug' if env == 'dev' else 'info' }}"  

  - name: TORCH - Start container
    community.docker.docker_compose_v2:
      project_src: "{{ project_path }}"
      project_name: "{{ project_name }}"
    environment:
      COMPOSE_IGNORE_ORPHANS: "1"
