- name: DSF FHIR - Get KDS test data
  unarchive:
    src: "{{ url }}"
    dest: "{{ project_path }}"
    remote_src: true
    creates: "{{ project_path }}/{{ url | basename }}"
 
- name: FHIR Server - Find KDS bundle files
  find:
    paths: >-
      {{ project_path }}/{{ url | basename | regex_replace('^(.*[^\.]+)\.[^\.]+$','\1') }}/resources
    patterns: "Bundle-mii-exa-test-data-bundle*.json"
    file_type: file
  register: kds_bundle_files
  changed_when: false
 
- name: FHIR Server - Upload KDS test data (one POST per found bundle file)
  include_tasks: _upload-kds-test-data-single.yml
  loop: "{{ kds_bundle_files.files }}"
  when: kds_bundle_files.files | length > 0
  loop_control:
    loop_var: bundle
    label: "{{ bundle.path }}"
  vars:
    bundle_path: "{{ bundle.path }}"