---
# tasks file for fdpg-keycloak
- name: Keycloak - Checkout FDPG Deployment
  include_role:
    name: common
    tasks_from: checkout-deploy-repo

- name: Keycloak - Get Certificate and Key from Storage
  include_role:
    name: common
    tasks_from: get-storage-file
  vars:
    storage_file_path: "{{ item.src }}"
    host_file_path: "{{ item.dest }}"
  loop:
  - src:  "secrets/{{ env }}/domain/fdpg.{{ env }}.ffg.de.crt"
    dest: "{{ secrets_path }}/fdpg.{{ env }}.ffg.de.crt"
  - src:  "secrets/{{ env }}/domain/fdpg.{{ env }}.ffg.de.key"
    dest: "{{ secrets_path }}/fdpg.{{ env }}.ffg.de.key"
  when: not letsencrypt_enabled

- name: Keycloak - Set Certificate and Key Path Variables
  set_fact:
    certificate_path: "{{ secrets_path }}/fdpg.{{ env }}.ffg.de.crt"
    private_key_path: "{{ secrets_path }}/fdpg.{{ env }}.ffg.de.key"
  when: not letsencrypt_enabled

- name: Keycloak - Get Certificate and Key from LetsEncrypt
  include_role:
    name: common
    tasks_from: certbot
  vars:
    certbot_register_email: info@tmf-ev.de
    certbot_register_domain: "{{ fdpg_auth_domain }}"
    certificates_path: "{{ secrets_path }}/letsencrypt"
    certbot_user_id: 101
    certbot_group_id: 101
    certbot_renewal_project_name: keycloak
    certbot_renewal_docker_compose_files:
    - "{{ deploy_path }}/proxy-docker-compose.yml"
  when: letsencrypt_enabled

- name: Keycloak - Get Keycloak environment config stats
  stat:
    path: "{{ deploy_path }}/data-portal/keycloak/.env"
  register: keycloak_env

- name: Keycloak - Get Keycloak default environment config stats
  stat:
    path: "{{ deploy_path }}/data-portal/keycloak/.env.default"
  register: keycloak_env_default

- name: Keycloak - Copy Keycloak default environment config
  copy:
    src: "{{ deploy_path }}/data-portal/keycloak/.env.default"
    dest: "{{ deploy_path }}/data-portal/keycloak/.env"
    owner: ubuntu
    group: ubuntu
    mode: u+rw,g-wx,o-rwx
    remote_src: true
  when: keycloak_env.stat.exists == false or keycloak_env.stat.ctime < keycloak_env_default.stat.ctime

- name: Keycloak - Read database password
  set_fact:
    kc_db_password: "{{ lookup('file', storage_path + '/secrets/' + env + '/keycloak/keycloak-db.password') }}"
    kc_admin_password: "{{ lookup('file', storage_path + '/secrets/' + env + '/keycloak/keycloak-admin.password') }}"
    kc_test_user_password: "{{ lookup('file', storage_path + '/secrets/' + env + '/keycloak/keycloak-user-test.password') }}"
  changed_when: false

- name: Keycloak - Setup Keycloak
  lineinfile:
    path: "{{ deploy_path }}/data-portal/keycloak/.env"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
  - regexp: '^KC_DB_PW='
    line:    "KC_DB_PW={{ kc_db_password }}"
  - regexp: '^KC_BOOTSTRAP_ADMIN_PASSWORD='
    line:    "KC_BOOTSTRAP_ADMIN_PASSWORD={{ kc_admin_password }}"
  - regexp: '^KC_HTTP_RELATIVE_PATH='
    line:    "KC_HTTP_RELATIVE_PATH=/"
  - regexp: '^KC_HOSTNAME='
    line:    'KC_HOSTNAME=https://{{ fdpg_auth_domain }}'
  - regexp: '^KC_HOSTNAME_ADMIN='
    line:    'KC_HOSTNAME_ADMIN=https://{{ fdpg_auth_domain }}'

- name: Keycloak - Set base url in init config
  replace:
    path: "{{ deploy_path }}/data-portal/keycloak/init/dataportal-realm.json"
    regexp: 'https://localhost'
    replace: "https://{{ fdpg_portal_domain }}"

- name: Keycloak - Start Keycloak service
  community.docker.docker_compose_v2:
    project_name: keycloak
    project_src: "{{ deploy_path }}/data-portal/keycloak"
    files:
    - docker-compose.yml
  register: keycloak_docker

- name: Keycloak - Copy proxy configuration
  template:
    src: nginx.conf.j2
    dest: "{{ deploy_path }}/nginx.conf"
    owner: ubuntu
    group: ubuntu
    mode: u=rw,g=r,o=r

- name: Keycloak - Copy proxy docker-compose.yml
  template:
    src: proxy-docker-compose.yml
    dest: "{{ deploy_path }}/proxy-docker-compose.yml"
    owner: ubuntu
    group: ubuntu
    mode: u=rw,g=r,o=r

- name: Keycloak - Start proxy
  community.docker.docker_compose_v2:
    project_name: keycloak
    project_src: "{{ deploy_path }}"
    files:
    - proxy-docker-compose.yml

- name: Keycloak - Wait for Keycloak
  uri:
    url: "https://{{ fdpg_auth_domain }}"
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: 12 # 12 * 5s = 60s
  delay: 5 # Every 5 seconds

- name: Keycloak - Create test user
  include_tasks: create-user.yml
  vars:
    admin_password: "{{ kc_admin_password }}"
    username: "test"
    first_name: "Test"
    last_name: "User"
    email: "foo@bar.baz"
    user_password: "{{ kc_test_user_password }}"
    kc_roles:
    - name: "DataportalUser"

- name: Keycloak - Create additional users
  include_tasks: create-user.yml
  vars:
    admin_password: "{{ kc_admin_password }}"
    username: "{{ kc_user.username }}"
    first_name: "{{ kc_user.first_name }}"
    last_name: "{{ kc_user.last_name }}"
    email: "{{ kc_user.username }}@bar.baz"
    user_password: "{{ lookup('file', kc_user.password_file) }}"
    kc_roles:
    - name: "DataportalUser"
  loop: "{{ additional_keycloak_user | default([]) }}"
  loop_control:
    loop_var: kc_user
  when: additional_keycloak_user is iterable

- name: Keycloak - Create additional clients
  include_tasks: create-client.yml
  vars:
    admin_password: "{{ kc_admin_password }}"
    client_id: "{{ kc_client.client_id }}"
  loop: "{{ additional_keycloak_client | default([]) }}"
  loop_control:
    loop_var: kc_client
  when: additional_keycloak_client is iterable


