galaxy_info:
  author: Mathias Rühle
  description: setup the central potal site of the FDPG
  company: Medizininformatik-Initiative
  license: Apache-2.0
  min_ansible_version: "2.1"
  platforms:
  - name: Ubuntu
    versions:
    - all
  galaxy_tags: []

dependencies: []
